# Generated by Django 4.0.6 on 2022-07-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_shorted', models.CharField(max_length=200)),
                ('description_full', models.TextField(max_length=10000)),
                ('main_photo', models.ImageField(max_length=500, upload_to='designs')),
                ('handle', models.CharField(choices=[('ST', 'Standard'), ('HD', 'Hidden')], default='ST', max_length=2)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('materials', models.ManyToManyField(to='Utils.material')),
                ('palette', models.ManyToManyField(to='Utils.palette')),
                ('photos', models.ManyToManyField(to='Utils.photos')),
                ('styles', models.ManyToManyField(to='Utils.style')),
            ],
        ),
    ]
